### ISSUE TITLE
Tests won't load after Angular 6 upgrade

### ISSUE THREAD

**Issue by nallarv** [HackedByChinese/ng2-idle#101] opened 2018-05-26 02:10 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

**Current behavior**
Tests are not getting executed after angular 6 upgrade with the latest ngIdle module. Currently we see a `Executed 0 of 0 ERROR (0.005 secs / 0 secs)` message as soon as I add ngIdle to the constructor of any component or service. The whole test run itself fails without any message.

**Expected behavior**
Tests should work fine or at least be able to load and report what the error is. 

**Minimal reproduction of the problem with instructions**
Create a brand new Angular 6 app using angular cli and add ngIdle to the constructor. The tests won't execute after that.

**Please tell us about your environment:**
Mac OS - 10.12.6
Chrome - 66.0.3359

* **@ng-idle version:** 6.0.0-beta.1

* **Angular version:** 6.0.2

* **Browser:** Chrome 66

* **Language:** Typescript

* **Node:** `node --version` =9.1.0

**Comment by nallarv** [comment] 2018-05-26 04:04
Here is how my code looks. As simple as it can get.
app.component.ts
`
import { Component } from '@angular/core';
import { DEFAULT_INTERRUPTSOURCES, Idle } from '@ng-idle/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  constructor(
    private readonly idle: Idle
  ) {

  }
}
`
app.component.spec.ts
`
import { TestBed, async } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { Idle } from '@ng-idle/core';

describe('AppComponent', () => {
  const idle = {
    setIdle: jasmine.createSpy('idle'),
    setTimeout: jasmine.createSpy('setTimeout'),
    setInterrupts: jasmine.createSpy('setInterrupts')
  };
  beforeEach(async(() => {
    TestBed.configureTestingModule({

      declarations: [
        AppComponent
      ],
      providers: [{ provide: Idle, useValue: idle }]
    }).compileComponents();
  }));
  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
  it(`should have as title 'app'`, async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app.title).toEqual('app');
  }));
  it('should render title in a h1 tag', async(() => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.debugElement.nativeElement;
    expect(compiled.querySelector('h1').textContent).toContain('Welcome to test-angular6-app2!');
  }));
});

`

**Comment by dreamid27** [comment] 2018-05-28 04:17
This package will be supported angular v6?

**Comment by dspies** [comment] 2018-05-31 17:43
I am having this issue as well, and I believe this is related to issue #99.  I commented out `import 'zone.js'` from the <pre>node_modules/@ng-idle/core/src/interruptsource.js</pre> and my tests began running again.

**Comment by nallarv** [comment] 2018-05-31 21:18
@dspies, Yup. That worked.  Surprising that it fails so silently. 
@HackedByChinese, could you please take a look at this [PR](https://github.com/HackedByChinese/ng2-idle/pull/103) and merge it if all is fine?

**Comment by HackedByChinese** [comment] 2018-05-31 22:04
Duplicate of #99

**Closed by HackedByChinese** 2018-05-31 22:04 UTC
