### ISSUE TITLE
Angular universal ssr - document is not defined

### ISSUE THREAD

**Issue by fadelguy** [HackedByChinese/ng2-idle#89] opened 2018-03-28 06:40 UTC
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/HackedByChinese/ng2-idle/blob/master/CONTRIBUTING.md#getting-help
```

Hi,

I'm using angular universal for server side rendering.
I'm getting error in html:
>document is not defined at new DocumentInterrupSource (webpack-internal:///225:23:34)
at createDefaultInterruptSources (webpack-interanl:///819:44:13)
at eval (webpack-internal:///819:47:32)

Please add support for angular universal.

* **@ng-idle version:** 2.0.0-beta.13

* **Angular version:** 5.2.9

* **Node:** `node --version` = 8.9.4

**Comment by HackedByChinese** [comment] 2018-03-29 12:53
duplicate of #77

**Closed by HackedByChinese** 2018-03-29 12:53 UTC
